[package]
name = "deepshield_ai"
edition = "2024.beta" # Edition 2024

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
deepshield_ai = "0x0"
